M48
; DRILL file {KiCad 6.0.9+dfsg-1} date Sat Nov 12 19:52:37 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-12T19:52:37+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C3.700
%
G90
G05
T1
X128.0Y-115.5
X142.0Y-101.5
T2
X130.54Y-112.96
X139.46Y-104.04
T3
X60.5Y-108.5
X135.0Y-34.0
X135.0Y-183.0
X209.5Y-108.5
T0
M30
